services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
      target: run-stage
      args:
        - JUPYTER_VERSION=notebook-6.3.0
        - WORK_DIR=/notebooks
    env_file:
      - .env
    container_name: amoopy
    user: "${USER_ID}:100" # Use the specified user ID and group ID
    ports:
      - "8090:8888" # Mapping host port 3011 to container port 8888
    volumes:
      - "./notebooks:/notebooks" # Bind mount host's notebooks directory
      - "./jupyter:/home/jovyan/.jupyter"
